spring:
  application:
    name: certificateService
---
server:
  port: 9011
  ssl:
    key-store: classpath:certificate-app.p12
    key-store-password: cert-app
    key-alias: certificate-app
    key-store-type: PKCS12
    key-store-provider: SUN
    enabled: true
    client-auth: want

