spring:
  application:
    name: client-app
---
server:
  port: 9008
  ssl:
    key-store: classpath:client-app.p12
    key-store-password: client-app
    key-alias: client-app
    key-store-type: PKCS12
    key-store-provider: SUN
    enabled: true
    client-auth: want
